# Site settings
title: sonsona.cat
email: miquel@sonsona.cat
description: > # this means to ignore newlines until "baseurl:"
  Along a path of learning and discovery
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sonsona.cat" # the base hostname & protocol for your site
twitter_username: msonsona
github_username:  msonsona

# Build settings
markdown: kramdown
# lsi: true

# GitHub Pages settings
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Permalinks
permalink: /:title/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Miquel"

# Plugins (previously Gems)
plugins:
  - jekyll-feed
  - emoji_for_jekyll
  - jekyll-sitemap

# Files
exclude: 
  - .env
  - s3_website.yml
keep_files: [uploads]

# Categories
category_archive:
  path: "category"
  slugify: true

# Projects Portfolio
portfolio_dir: "projects"
skip_related_projects: true
